export function destinations() {
  return {
    mountBromo: {
      id: "dst-bromo-001",
      name: "Gunung Bromo",
      slug: "gunung-bromo",
      tagline: "Sunrise di lautan pasir",
      description:
        "Gunung berapi aktif dengan kawasan lautan pasir dan panorama sunrise paling ikonik di Indonesia. Cocok untuk wisatawan pemula karena akses tidak memerlukan pendakian teknis.",
      terrain: ["gunung", "savana"],
      activities: ["sunrise", "sightseeing", "photography", "off-road"],
      difficulty: "ramah-pemula",
      bestSeason: ["kering", "Jul-Okt"],
      location: {
        province: "Jawa Timur",
        regency: "Probolinggo",
        coordinate: { latitude: -7.9425, longitude: 112.9531 },
        accessPoint: {
          name: "Cemoro Lawang",
          coordinate: { latitude: -7.9228, longitude: 112.9765 },
        },
      },
      access: {
        description:
          "Dari Surabaya via Probolinggo, lanjut ke Cemoro Lawang. Kendaraan pribadi atau sewa jeep.",
        transportModes: ["mobil", "jeep", "motor"],
        estimatedTravelTime: "±4 jam dari Surabaya",
        distanceKm: 140,
      },
      facilities: {
        toilet: true,
        warung: true,
        spotRequest: true,
        mushola: false,
        parkingArea: true,
        homestayNearby: true,
      },
      entryFee: "RP 29.000 - 34.000 (wisatawan domestik/asing)",
      images: ["/images/bromo-1.jpg", "/images/bromo-2.jpg"],
      tags: ["sunrise", "jeep", "ramah-pemula", "sejuk", "garda-tropika"],
      elevationMeters: 2329,
      guideRequired: false,
      createdAt: new Date("2026-01-10T00:00:00.000Z").toISOString(),
      updatedAt: new Date("2026-01-10T00:00:00.000Z").toISOString(),
    },
    papandayan: {
      id: "dst-papandayan-002",
      name: "Gunung Papandayan",
      slug: "gunung-papandayan",
      tagline: "Camping di padang edelweiss",
      description:
        "Gunung api dengan taman edelweiss, kawah aktif, dan spot camping favorit untuk pemula. Kombinasi pemandangan gunung, hutan, dan kawah yang menakjubkan.",
      terrain: ["gunung", "camping-ground"],
      activities: ["camping", "hiking", "photography", "sightseeing"],
      difficulty: "ramah-pemula",
      bestSeason: ["kering", "Mei-Sep"],
      location: {
        province: "Jawa Barat",
        regency: "Garut",
        coordinate: { latitude: -7.3244, longitude: 107.7335 },
        accessPoint: {
          name: "Basecamp Cisurupan",
          coordinate: { latitude: -7.3195, longitude: 107.786 },
        },
      },
      access: {
        description:
          "Dari Bandung via Garut menuju Cisurupan. Jalan beraspal hingga basecamp, lanjut trekking singkat.",
        transportModes: ["mobil", "motor", "bus"],
        estimatedTravelTime: "±3.5 jam dari Bandung",
        distanceKm: 75,
      },
      facilities: {
        toilet: true,
        warung: true,
        spotRequest: true,
        mushola: true,
        parkingArea: true,
        homestayNearby: true,
      },
      entryFee: "RP 40.000 (wisatawan domestik)",
      images: ["/images/papandayan-1.jpg", "/images/papandayan-2.jpg"],
      tags: ["camping", "edelweiss", "kawah", "ramah-pemula", "jeep"],
      elevationMeters: 2665,
      guideRequired: false,
      createdAt: new Date("2026-01-12T00:00:00.000Z").toISOString(),
      updatedAt: new Date("2026-01-12T00:00:00.000Z").toISOString(),
    },
    bukitMoko: {
      id: "dst-moko-003",
      name: "Bukit Moko",
      slug: "bukit-moko",
      tagline: "Langit Bandung dari ketinggian",
      description:
        "Perbukitan di utara Bandung dengan spot sunrise dan titik observasi langit. Akses mudah, cocok untuk perjalanan singkat setengah hari.",
      terrain: ["bukit"],
      activities: ["sunrise", "photography", "off-road"],
      difficulty: "ramah-pemula",
      bestSeason: ["Sep-Nov", "kering"],
      location: {
        province: "Jawa Barat",
        regency: "Bandung Barat",
        coordinate: { latitude: -6.8456, longitude: 107.6231 },
        accessPoint: {
          name: "Cimenyan",
          coordinate: { latitude: -6.869, longitude: 107.64 },
        },
      },
      access: {
        description:
          "Dari pusat Bandung via Lembang menuju Cimenyan. Rute off-road ringan, direkomendasikan menggunakan motor atau mobil tinggi ground clearance.",
        transportModes: ["motor", "mobil"],
        estimatedTravelTime: "±1.5 jam dari pusat Bandung",
        distanceKm: 25,
      },
      facilities: {
        toilet: false,
        warung: true,
        spotRequest: false,
        mushola: false,
        parkingArea: true,
        homestayNearby: false,
      },
      entryFee: "RP 15.000",
      images: ["/images/bukit-moko-1.jpg"],
      tags: ["sunrise", "bandung", "city-view", "singkat", "budget"],
      elevationMeters: 1345,
      guideRequired: false,
      createdAt: new Date("2026-01-15T00:00:00.000Z").toISOString(),
      updatedAt: new Date("2026-01-15T00:00:00.000Z").toISOString(),
    },
    prau: {
      id: "dst-prau-004",
      name: "Gunung Prau",
      slug: "gunung-prau",
      tagline: "Lautan awan di atas Dieng",
      description:
        "Salah satu gunung terbaik untuk melihat lautan awan. Track populer untuk pendaki pemula-menengah dengan pemandangan Rangga dan Sindoro dari puncak.",
      terrain: ["gunung", "camping-ground"],
      activities: ["hiking", "camping", "sunrise", "sightseeing", "photography"],
      difficulty: "menengah",
      bestSeason: ["kering", "Apr-Sep"],
      location: {
        province: "Jawa Tengah",
        regency: "Wonosobo",
        coordinate: { latitude: -7.2256, longitude: 109.9933 },
        accessPoint: {
          name: "Patak Banteng",
          coordinate: { latitude: -7.171, longitude: 109.96 },
        },
      },
      access: {
        description:
          "Via Patak Banteng atau Dieng. Track ±3-4 jam pendakian dengan pemandangan savana.",
        transportModes: ["mobil", "motor", "elf", "open-trip"],
        estimatedTravelTime: "±1.5 jam dari Wonosobo",
        distanceKm: 25,
      },
      facilities: {
        toilet: true,
        warung: true,
        spotRequest: true,
        mushola: false,
        parkingArea: true,
        homestayNearby: true,
      },
      entryFee: "RP 25.000",
      images: ["/images/prau-1.jpg", "/images/prau-2.jpg"],
      tags: ["lautan-awan", "camping", "savana", "dieng", "open-trip"],
      elevationMeters: 2565,
      guideRequired: false,
      createdAt: new Date("2026-01-18T00:00:00.000Z").toISOString(),
      updatedAt: new Date("2026-01-18T00:00:00.000Z").toISOString(),
    },
  } as const;
}